export const images = {
  defaultUser: require("./images/defaultUser.jpg"),
  camera: require("./images/camera.png"),
  folder: require("./images/folder.png"),
  photo: require("./images/image.png"),
  location: require("./images/location.png"),
  poll: require("./images/poll.png"),
  users: require("./images/users.png"),
  theme: require("./images/theme.png"),
  bg: require("./images/bg.jpg"),
  flash: require("./images/flash.png"),
  flip: require("./images/flip.png"),
  speed: require("./images/speed.png"),
  timer: require("./images/timer.png"),
};
